# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}

    - name: set up Java 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Uninstall NDK
      run: |
        sudo ${ANDROID_HOME}/tools/bin/sdkmanager --uninstall 'ndk-bundle'

    - name: Build APKs
      run: |
        echo "Generating ApiDemos (Java) APKs"
        cd $GITHUB_WORKSPACE/ApiDemos/java
        ./gradlew assembleV3 assembleGms
        cp ./app/build/outputs/apk/gms/debug/app-gms-debug.apk $GITHUB_WORKSPACE/ApiDemos-java-gms-debug.apk
        cp ./app/build/outputs/apk/v3/debug/app-v3-debug.apk $GITHUB_WORKSPACE/ApiDemos-java-v3-debug.apk

        echo "Generating Kotlin (Kotlin) APKs"
        cd $GITHUB_WORKSPACE/ApiDemos/kotlin
        ./gradlew assembleV3 assembleGms
        cp ./app/build/outputs/apk/gms/debug/app-gms-debug.apk $GITHUB_WORKSPACE/ApiDemos-kotlin-gms-debug.apk
        cp ./app/build/outputs/apk/v3/debug/app-v3-debug.apk $GITHUB_WORKSPACE/ApiDemos-kotlin-v3-debug.apk

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        extra_plugins: |
          "@semantic-release/commit-analyzer"
          "@semantic-release/release-notes-generator"
          "@google/semantic-release-replace-plugin"
          "@semantic-release/git
          "@semantic-release/github
      env:
        GH_TOKEN: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
